-keepattributes *Annotation*
-keep class * extends androidx.room.RoomDatabase
-keep @androidx.room.Entity class *
-keep class com.oldpopguard.block.rule.** { *; }
-keep class com.oldpopguard.block.data.** { *; }
